### PR TITLE
(issue#10)Enable producer to push camera live streams to kinesis

### PR DESCRIPTION
**Pull request by backdoorcodr**
*Issue # 10: This branch is still Work in Progress (WIP)* 

*Description of changes:*
From my understanding until I have looked into the code and executed it (until now in Java only, trying in cpp but facing issues which have been reported already), I have understood that the sample application in java reads the stored frames from local drive and pushes them to the kinesis stream. However, what would be more interesting is to have a producer application that directly streams from the camera and push it to kinesis. 

I have created createCameraMediaSource() method, CameraMediaSource class and CameraFrameSource class available in the com.amazonaws.kinesisvideo.java.mediasource.camera package. Since there is no generic support in Java for handling cameras, therefore for now I am trying to use [webcam-capture-api](https://github.com/sarxos/webcam-capture) that can perform the streaming from the camera feed by using the `Webcam` class that wraps webcam device obtained from webcam driver. 

My output until now are attached in the screenshots below: 

debugging_console

output

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by huynhthanhviet** [comment]
Hi,
Thanks for your implementation with camera. Now, I can streaming from build-in camera (osx) to kinesis. However, after about 45 second. the video is stucked. 
One more thing that make me confuse is how to define the codecprivatedata as you did?

**Comment by anmol1ratn** [comment]
Hello @backdoorcodr,

I have to make a project which requires the use of live feeds from three cameras simultaneously. I got the demo provided by the AWS demo java sdk which sends prestored H264 encoded frames to the Kinesis stream and it worked fine for me. I was able to send frames to Kinesis Stream. But then, for my project, I searched the internet and I found this thread, which really matches my interest. I downloaded the sdk from this repo (https://github.com/backdoorcodr/amazon-kinesis-video-streams-producer-sdk-java) and tried playing around. I'm using **IntelliJ Idea** IDE and I don't know why but there are some issues with the dependencies in my **pom.xml** file. For example, there are two packages namely **xuggler** and **geotoolkit** which are used in the implementing **CameraMediaSource** and **CameraMediaSource**  and **CameraFrameSource** classes. As far as I know, the **pom.xml** file is modified to download dependencies and get the project working and that I don't have to manually download the jar files and add them to classpath. But the problem is that it is not working out for me. When I bulid the project it shows an error that says:
**java: package com.xuggle.xuggler does not exist**
When I downloaded **xuggler.jar** and manually added the jar file to classpath, things worked fine for **xuggler** but then **geotoolkit** was the problem. The error was:  **java: package org.geotoolkit.display3d.utils does not exist**

Please help me in understanding what I'm missing here? Or there's something extra I have to do? Or that even though **pom.xml** is modified, I still have to download jar files and add them to classpath manually.

PS: I haven't changed anything in your sdk (the sdk downloaded from the above link) except changing the AWS credentials and Regions for my account.

**Comment by Ga22be** [comment]
@anmol1ratn xuggler is no longer maintained so i guess thats why it isn't available for pom.xml to download.

**Comment by anmol1ratn** [comment]
@backdoorcodr 

Please tell me how to fix this.

Exception in thread "main" java.lang.IllegalStateException: FATAL DEPLOYMENT ERROR: This app is built to run with version 1.2 of the libKinesisVideoProducerJNI.so library, but version 1.5 was found on this device.

**Comment by MushMal** [comment]
@anmol1ratn the error indicates that there is a mismatch between Java interface version and the native library version. Could you please ensure you are building/using same versions? The best would be to use the tips of the git repositories to ensure they are in-sync.

We understand that building the native repository is a hassle currently (if you haven't yet got it built there is a long process building open source components which takes 99% of the build time). We are working on making this process easier.

**Comment by backdoorcodr** [comment]
Hi @huynhthanhviet , apologies for replying late. That is a great information, let me regenerate this issue on my machine and get back to you.

**Comment by backdoorcodr** [comment]
Hi @anmol1ratn, Many thanks for trying. As @MushMal mentioned that this is because of the mismatch between the interface version and native library version. Can you try and get back to me? :)

**Comment by anmol1ratn** [comment]
Thanks @backdoorcodr  and @MushMal for your responses.

Let me start with a bit of background.
I get that the sdk version of this respository is 1.2 but version of libKinesisVideoProducerJNI.so library (which I used the same which comes preloaded in the latest aws kinesis sdk) is 1.5

I don't know how to build libKinesisVideoProducerJNI.so library for version 1.2 of aws kinesis sdk-java.

I cloned the **latest** cpp sdk, followed necessary steps, and then ran ./java-install-script from inside the **kinesis-video-native-build** folder but still it's for version 1.5 and not for 1.2. I don't know how to produce libKinesisVideoProducerJNI.so for version 1.2 and not version 1.5. Please help me with this.

**Comment by MushMal** [comment]
As a general rule of thumb, we recommend pulling the latest from both Java and CPP SDKs which will have the corresponding interface versions. In this case the library you are trying to use has older code so you need to get the corresponding version of the CPP and build that. You can look at the git history in CPP to see when the version of the interface changed and checkout the version and build it.

The corresponding file to look into is 

<code>
amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-producer-jni/src/source/com/amazonaws/kinesis/video/producer/jni/NativeProducerInterface.cpp
</code>

**Comment by backdoorcodr** [comment]
@MushMal @unicornss @zhiyua-git Hello all, 

Let me know if a PR is welcome to work on this enhancement. I am happy to make changes to my old PR for this extension and submit it.

**Comment by backdoorcodr** [comment]
@MushMal sounds great ! (:+1: ) Let me update my PR and get back to you guys. Your comments are also very welcome on my existing PR.

**Comment by Shvm** [comment]
@backdoorcodr First of all thank you to create a branch on feeding live web cam stream to kinesis 
I have clone your repo for amazon-kinesis-video-streams-producer-sdk-java. 
I somehow got the project working by resolving dependencies of xugglr and geotoolkit.
But now the code is breaking at this point 
[line](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/blob/master/src/main/java/com/amazonaws/kinesisvideo/internal/producer/jni/NativeKinesisVideoProducerJni.java#L235)

with the following exception:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(Lcom/amazonaws/kinesisvideo/producer/DeviceInfo;)J
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(Native Method)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:219)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:231)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:197)
	at com.amazonaws.kinesisvideo.client.NativeKinesisVideoClient.initialize(NativeKinesisVideoClient.java:112)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:106)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:79)
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:48)`


Please help me in this regard or give me some direction.

**Comment by Shvm** [comment]
@backdoorcodr I have fixed the issue that i mentioned above, now I am getting EventType: Persisted
but the preview is unable to stream my live feed.
Find the issue here [issue#65](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/65)

Looking forward to suggestion/direction/correction/help.

**Comment by BodapatlaKiranReddy** [comment]
@Shvm 

May i know how did you resolve  xugglr and geotoolkit dependencies, when i go through the issue with dependencies  the explaination is they are no longer available.

**Comment by Shvm** [comment]
@BodapatlaKiranReddy As far as I remember, I downloaded and have put those jar manually in my project.

**Comment by BodapatlaKiranReddy** [comment]
@Shvm Thanks for your quick response.

**Comment by BodapatlaKiranReddy** [comment]
@backdoorcodr 
As the latest producer SDK doesn't have cameraMediaSource class how to integrate the webcam with kinesis video stream. But
[ https://github.com/backdoorcodr/amazon-kinesis-video-streams-producer-sdk-java](url) tried with this but issues with native library version and dependencies also.

Any suggestion on how to push live from webcam to KVS in java  will be really appreciated

**Pull request closed without merging**
